name: Find_and_Replace
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "ublox"
          replace: "ublox_dog"
          include: "README.md" # Will match all README.md files in any nested directory
