on: [push]

jobs:
  find-and-replace-job:
    runs-on: ubuntu-latest
    name: 'Find and replace on a string'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run find-and-replace to remove refs/heads/
        uses: mad9000/actions-find-and-replace-string@1
        id: findandreplace
        with:
          # source: ${{ github.ref }}
          source: "README.md" # Will match all README.md files in any nested directory
          find: 'ublox'
          replace: 'ublox_dog'
      - name: Get the above output
        run: echo "The replaced value is ${{ steps.findandreplace.outputs.value }}"
